/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package me;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author angga
 */
public class FormServiceMesinUser extends javax.swing.JInternalFrame {
DefaultComboBoxModel model = new DefaultComboBoxModel();
 DefaultComboBoxModel model2 = new DefaultComboBoxModel();
 DefaultComboBoxModel model3 = new DefaultComboBoxModel();

    Connection c = null;
    ResultSet r = null;
    /**
     * Creates new form FormServiceMesinUser
     */
    public FormServiceMesinUser() {
        initComponents();
        this.setLocation(50, 0);
        setModel();
        cbMesinId.setModel(model);
        setModelPic();
        cbNmPic.setModel(model2);
        setModelPekerjaan();
        cbKdPekerjaan.setModel(model3);
        BersihField();
        textServiceFalse();
        tombolServiceFalse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tUraianProblem = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tKdService = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bHapus = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        bTutup = new javax.swing.JButton();
        tDepartement = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbMenit = new javax.swing.JLabel();
        cbShift = new javax.swing.JComboBox();
        cbKdPekerjaan = new javax.swing.JComboBox();
        bCari = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        tNmPengaju = new javax.swing.JTextField();
        bUbah = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        cbNmPic = new javax.swing.JComboBox();
        cbMesinId = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tTindakan = new javax.swing.JTextArea();
        tTglAju = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tPenyebab = new javax.swing.JTextArea();
        tMesinStop = new javax.swing.JTextField();
        tJamSelesai1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tJamSelesai2 = new javax.swing.JTextField();
        tJamMulai2 = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tJamMulai1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tDurasi = new javax.swing.JTextField();
        cbCari = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        bBatal = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setIconifiable(true);
        setTitle("Form Service Mesin");

        tUraianProblem.setColumns(20);
        tUraianProblem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tUraianProblem.setRows(5);
        tUraianProblem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tUraianProblemAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tUraianProblemAncestorRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(tUraianProblem);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel31.setText("Tanggal Pengajuan");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setText("Durasi");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Kode Service");

        tKdService.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tKdService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKdServiceActionPerformed(evt);
            }
        });
        tKdService.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tKdServiceKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Mesin");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Teknisi");

        bHapus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon delete.png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel36.setText("Shift");

        bTutup.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/tutup.png"))); // NOI18N
        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });

        tDepartement.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tDepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDepartementActionPerformed(evt);
            }
        });
        tDepartement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tDepartementKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setText("Uraian Problem");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel33.setText("Diajukan Oleh");

        lbMenit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbMenit.setText("Menit");

        cbShift.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        cbKdPekerjaan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKdPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKdPekerjaanActionPerformed(evt);
            }
        });

        bCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon cari.png"))); // NOI18N
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel34.setText("Departement");

        tCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCariKeyTyped(evt);
            }
        });

        tNmPengaju.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tNmPengaju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNmPengajuActionPerformed(evt);
            }
        });
        tNmPengaju.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNmPengajuKeyTyped(evt);
            }
        });

        bUbah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon edit.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bTambah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon tambah.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        cbNmPic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNmPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNmPicActionPerformed(evt);
            }
        });

        cbMesinId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMesinId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesinIdActionPerformed(evt);
            }
        });

        tTindakan.setColumns(20);
        tTindakan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tTindakan.setRows(5);
        tTindakan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tTindakanAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(tTindakan);

        tTglAju.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tTglAju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTglAjuActionPerformed(evt);
            }
        });
        tTglAju.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tTglAjuKeyTyped(evt);
            }
        });

        tPenyebab.setColumns(20);
        tPenyebab.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tPenyebab.setRows(5);
        tPenyebab.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tPenyebabAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tPenyebab);

        tMesinStop.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tMesinStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMesinStopActionPerformed(evt);
            }
        });
        tMesinStop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tMesinStopKeyTyped(evt);
            }
        });

        tJamSelesai1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tJamSelesai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJamSelesai1ActionPerformed(evt);
            }
        });
        tJamSelesai1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tJamSelesai1KeyTyped(evt);
            }
        });

        jLabel7.setText(".");

        jLabel4.setText(".");

        tJamSelesai2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tJamSelesai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJamSelesai2ActionPerformed(evt);
            }
        });
        tJamSelesai2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tJamSelesai2KeyTyped(evt);
            }
        });

        tJamMulai2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tJamMulai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJamMulai2ActionPerformed(evt);
            }
        });
        tJamMulai2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tJamMulai2KeyTyped(evt);
            }
        });

        bSimpan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon save.png"))); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Service Mesin");

        tJamMulai1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tJamMulai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJamMulai1ActionPerformed(evt);
            }
        });
        tJamMulai1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tJamMulai1KeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setText("Mesin Stop");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel29.setText("Jam Selesai");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Jenis Pekerjaan");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel30.setText("Jam Mulai");

        tDurasi.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDurasiActionPerformed(evt);
            }
        });
        tDurasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tDurasiKeyTyped(evt);
            }
        });

        cbCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kolom", "Kode Service" }));
        cbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCariActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel28.setText("Penyebab");

        bBatal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon batal.png"))); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel32.setText("Tindakan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel19)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(tKdService)
                    .addComponent(tMesinStop, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKdPekerjaan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMesinId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbNmPic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36)
                    .addComponent(jLabel32))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tTglAju, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addComponent(tNmPengaju, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tDepartement)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tDurasi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbMenit)
                            .addGap(29, 29, 29))
                        .addComponent(cbShift, javax.swing.GroupLayout.Alignment.TRAILING, 0, 101, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tJamMulai1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addComponent(tJamSelesai1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tJamSelesai2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                .addComponent(tJamMulai2)))))
                .addGap(197, 197, 197))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bTambah)
                        .addGap(80, 80, 80)
                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(bUbah))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTutup)
                    .addComponent(bHapus))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tKdService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbMesinId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbNmPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbKdPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tMesinStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tJamMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(tJamMulai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tJamSelesai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(tJamSelesai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(lbMenit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(tTglAju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNmPengaju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)))
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSimpan))
                        .addComponent(bBatal))
                    .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void tombolServiceFalse() {
        bSimpan.setEnabled(false);
        bBatal.setEnabled(false);
        bUbah.setEnabled(false);
        bHapus.setEnabled(false);
        bCari.setEnabled(false);
        bTutup.setEnabled(true);
    }

    private void textServiceFalse() {
        tKdService.setEnabled(true);
        cbMesinId.setEnabled(false);
        cbNmPic.setEnabled(false);
        cbKdPekerjaan.setEnabled(false);
        tMesinStop.setEnabled(false);
        tUraianProblem.setEnabled(false);
        tPenyebab.setEnabled(false);
        tTindakan.setEnabled(false);
        tJamMulai1.setEnabled(false);
        tJamMulai2.setEnabled(false);
        tJamSelesai1.setEnabled(false);
        tJamSelesai2.setEnabled(false);
        tDurasi.setEnabled(false);
        tTglAju.setEnabled(false);
        tNmPengaju.setEnabled(false);
        tDepartement.setEnabled(false);
        cbShift.setEnabled(false);
        tCari.setEnabled(false);
    }

    private void textServiceTrue() {
        tKdService.setEnabled(true);
        cbMesinId.setEnabled(true);
        cbNmPic.setEnabled(true);
        cbKdPekerjaan.setEnabled(true);
        tMesinStop.setEnabled(true);
        tUraianProblem.setEnabled(true);
        tPenyebab.setEnabled(true);
        tTindakan.setEnabled(true);
        tJamMulai1.setEnabled(true);
        tJamMulai2.setEnabled(true);
        tJamSelesai1.setEnabled(true);
        tJamSelesai2.setEnabled(true);
        tDurasi.setEnabled(true);
        tTglAju.setEnabled(true);
        tNmPengaju.setEnabled(true);
        tDepartement.setEnabled(true);
        cbShift.setEnabled(true);
        tCari.setEnabled(false);
    }

    private void BersihField() {
        tKdService.setText("");
        cbMesinId.setSelectedItem("");
        cbNmPic.setSelectedItem("");
        cbNmPic.setSelectedItem("");
        cbKdPekerjaan.setSelectedItem("");
        tMesinStop.setText("");
        tUraianProblem.setText("");
        tPenyebab.setText("");
        tTindakan.setText("");
        tJamMulai1.setText("");
        tJamMulai2.setText("");
        tJamSelesai1.setText("");
        tJamSelesai2.setText("");
        tDurasi.setText("");
        tTglAju.setText("");
        tTglAju.setText("");
        tTglAju.setText("");
        tNmPengaju.setText("");
        tDepartement.setText("");
        cbShift.setSelectedItem(1);
        tCari.setText("");
    }
public final void setModel(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/maintenance"; //disesuaikan
            String user="root";//disesuaikan
            String pass="";//disesuaikan
            c = DriverManager.getConnection(url,user,pass);
 
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("select * from mesin");
            while(rs.next()){
                String p1 = rs.getString("mesin_id")+"-"+rs.getString("nm_mesin");
                model.addElement(p1);
            }
        } catch (Exception e) {
            System.out.println("gagal");
        }
    }
public final void setModelPic(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/maintenance"; //disesuaikan
            String user="root";//disesuaikan
            String pass="";//disesuaikan
            c = DriverManager.getConnection(url,user,pass);
 
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("select * from pic");
            while(rs.next()){
                String p1 = rs.getString("nik")+"-"+rs.getString("nm_pic");
                model2.addElement(p1);
                }           
        } catch (Exception e) {
            System.out.println("gagal");
        }
    }
public final void setModelPekerjaan(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/maintenance"; 
            String user="root";
            String pass="";
            c = DriverManager.getConnection(url,user,pass);
 
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("select * from jenis_pekerjaan");
            while(rs.next()){
                String p1 = rs.getString("kd_pekerjaan")+"-"+rs.getString("gol_pekerjaan");
                model3.addElement(p1);
            }
        } catch (Exception e) {
            System.out.println("gagal");
        }
    }

    private void pilihKolomCari() {
        if (cbCari.getSelectedItem().equals("Pilih Kolom")) {
            tCari.setEnabled(false);
        } else {
            tCari.setEnabled(true);
            bCari.setEnabled(true);
            tCari.requestFocus();
        }
    }

    private void BukaKoneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/maintenance", "root", "");
            System.out.println("Koneksi sukses");
        } catch (ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void Simpan() {
        String kdservice = tKdService.getText();
        try {
            PreparedStatement pStatement = c.prepareStatement("INSERT INTO service_mesin"
                    + "(kd_service,mesin_id,nik,kd_pekerjaan,mesin_stop,uraian_problem,"
                    + "penyebab,tindakan,jam_mulai,jam_selesai,durasi,tgl_pengajuan,diajukan_oleh,departement,shift)"
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pStatement.setString(1, tKdService.getText());
            String p1 = cbMesinId.getSelectedItem().toString();
            String p2 = p1.substring(0, 7);
            pStatement.setString(2, p2);
            String param1 = cbNmPic.getSelectedItem().toString();
            String param2 = param1.substring(0, 8);
            pStatement.setString(3, param2);
            String params1 = cbKdPekerjaan.getSelectedItem().toString();
            String params2 = params1.substring(0, 5);
            pStatement.setString(4, params2);
            pStatement.setString(5, tMesinStop.getText());
            pStatement.setString(6, tUraianProblem.getText());
            pStatement.setString(7, tPenyebab.getText());
            pStatement.setString(8, tTindakan.getText());
            String jmM1 = tJamMulai1.getText();
            String jmM2 = tJamMulai2.getText();
            String jmMlai = jmM1 + "." + jmM2;
            pStatement.setString(9, jmMlai);
            String jmS1 = tJamSelesai1.getText();
            String jmS2 = tJamSelesai2.getText();
            String jmSls = jmS1 + "." + jmS2;
            pStatement.setString(10, jmSls);
            String dRS = tDurasi.getText();
            String Drs = dRS + " menit";
            pStatement.setString(11, Drs);
            pStatement.setString(12, tTglAju.getText());
            pStatement.setString(13, tNmPengaju.getText());
            pStatement.setString(14, tDepartement.getText());
            pStatement.setString(15, cbShift.getSelectedItem().toString());
            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this,
                        "Penambahan sukses", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                BersihField();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Penambahan gagal", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            c.close();
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
            JOptionPane.showMessageDialog(null, "Gagal menyimpan \nKode Service kembar :" + "\nKode Service [ " + kdservice + " ] telah ada, "
                    + "atau data yang Anda masukkan tidak sesuai format dengan yang diminta !");
            tKdService.setFocusable(true);
        }
    }

    private void ubah() {
        String kode = tKdService.getText();
        try {
            String message = "Apakah anda yakin akan mengubah semua data" + "\ndengan kode service :" + kode;
            int pesan = JOptionPane.showConfirmDialog(null, message, "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
            if (pesan == 0) {
            PreparedStatement pStatement = c.prepareStatement("UPDATE service_mesin SET mesin_id=?,nik=?,kd_pekerjaan=?,"
                    + "mesin_stop=?,uraian_problem=?,penyebab=?,tindakan=?,jam_mulai=?,jam_selesai=?,durasi=?,tgl_pengajuan=?,"
                    + "diajukan_oleh=?,departement=?, shift=? WHERE kd_service=?");
            String p1 = cbMesinId.getSelectedItem().toString();
            String p2 = p1.substring(0, 7);
            pStatement.setString(1, p2);
            String param1 = cbNmPic.getSelectedItem().toString();
            String param2 = param1.substring(0, 8);
            pStatement.setString(2, param2);
            String params1 = cbKdPekerjaan.getSelectedItem().toString();
            String params2 = params1.substring(0, 5);
            pStatement.setString(3, params2);
            pStatement.setString(4, tMesinStop.getText());
            pStatement.setString(5, tUraianProblem.getText());
            pStatement.setString(6, tPenyebab.getText());
            pStatement.setString(7, tTindakan.getText());
            String jmM1 = tJamMulai1.getText();
            String jmM2 = tJamMulai2.getText();
            String jmMlai = jmM1 + "." + jmM2;
            pStatement.setString(8, jmMlai);
            String jmS1 = tJamSelesai1.getText();
            String jmS2 = tJamSelesai2.getText();
            String jmSls = jmS1 + "." + jmS2;
            pStatement.setString(9, jmSls);
            String dRS = tDurasi.getText();
            String Drs = dRS + " menit";
            pStatement.setString(10, Drs);
            pStatement.setString(11, tTglAju.getText());
            pStatement.setString(12, tNmPengaju.getText());
            pStatement.setString(13, tDepartement.getText());
            pStatement.setString(14, cbShift.getSelectedItem().toString());
            pStatement.setString(15, tKdService.getText());
            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Edit sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                BersihField();
            } else {
                JOptionPane.showMessageDialog(null, "Edit gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            textServiceFalse();
            tombolServiceFalse();
            BersihField();
                        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal, atau data yang Anda masukkan tidak sesuai dengan yang diminta !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void hapus() {
        String kode = tKdService.getText();
        try {
            String message = "Apakah anda yakin akan menghapus semua data" + "\ndengan kode service :" + kode;
            int pesan = JOptionPane.showConfirmDialog(null, message, "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
            if (pesan == 0) {
                PreparedStatement pStatement = c.prepareStatement("DELETE FROM service_mesin WHERE kd_service=?");
                pStatement.setString(1, tKdService.getText());
                if (pStatement.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Berhasil menghapus", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                    BersihField();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Hapus gagal", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                pStatement.close();
                c.close();
                BersihField();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal " + e.toString());
        }
    }

    private void cari() {
        String param = tCari.getText();
        try {
            String kolom;
            if (cbCari.getSelectedItem().equals("Kode Service")) {
                kolom = "kd_service";
            } else {
                kolom = "";
            }
            Statement s = c.createStatement();
            String sql = "SELECT service_mesin.kd_service, service_mesin.mesin_id, mesin.nm_mesin, service_mesin.nik, pic.nm_pic, "
                    + "service_mesin.kd_pekerjaan, jenis_pekerjaan.gol_pekerjaan, service_mesin.mesin_stop, service_mesin.uraian_problem, service_mesin.penyebab, "
                    + "service_mesin.tindakan, service_mesin.jam_mulai, service_mesin.jam_selesai, service_mesin.durasi,"
                    + "service_mesin.tgl_pengajuan, service_mesin.diajukan_oleh, service_mesin.departement, service_mesin.shift "
                    + "FROM service_mesin, mesin, pic, jenis_pekerjaan WHERE service_mesin.mesin_id = mesin.mesin_id "
                    + "AND service_mesin.nik=pic.nik AND service_mesin.kd_pekerjaan = jenis_pekerjaan.kd_pekerjaan AND service_mesin." + kolom +  " = '"+ param +"'";
           r = s.executeQuery(sql);
            if (r.next()) {
                textServiceTrue();
                bUbah.setEnabled(true);
                bHapus.setEnabled(true);
                tKdService.setText(r.getString("service_mesin.kd_service"));
                String msnId = r.getString("service_mesin.mesin_id");
                String MsnId = r.getString("mesin.nm_mesin");
                String Mesin_id = msnId+"-"+MsnId;
                cbMesinId.setSelectedItem(Mesin_id);
                String nik = r.getString("service_mesin.nik");
                String nIk = r.getString("pic.nm_pic");
                String Nik = nik+"-"+nIk;
                cbNmPic.setSelectedItem(Nik);
                String pkrjaan = r.getString("service_mesin.kd_pekerjaan");
                String pKrjaan = r.getString("jenis_pekerjaan.gol_pekerjaan");
                String Pkrjaan = pkrjaan+"-"+pKrjaan;
                cbKdPekerjaan.setSelectedItem(Pkrjaan);
                tMesinStop.setText(r.getString("service_mesin.mesin_stop"));
                tUraianProblem.setText(r.getString("service_mesin.uraian_problem"));
                tPenyebab.setText(r.getString("service_mesin.penyebab"));
                tTindakan.setText(r.getString("service_mesin.tindakan"));
                String jMl = r.getString("service_mesin.jam_mulai");
                int i1 = jMl.length();
                String vBv = jMl.substring(0, 2);
                tJamMulai1.setText(vBv);
                tJamMulai1.setEnabled(false);
                int i = i1 - 2;
                String bvb = jMl.substring(i, i1);
                tJamMulai2.setText(bvb);
                tJamMulai2.setEnabled(false);
                String jSl = r.getString("service_mesin.jam_selesai");
                int k1 = jSl.length();
                String kmk = jSl.substring(0, 2);
                tJamSelesai1.setText(kmk);
                tJamSelesai1.setEnabled(false);
                int k = k1 - 2;
                String mkm = jSl.substring(k, k1);
                tJamSelesai2.setText(mkm);
                tJamSelesai2.setEnabled(false);
                String drs = r.getString("service_mesin.durasi");
                int ii = drs.length();
                String mnt = drs.substring(0, ii - 6);
                tDurasi.setText(mnt);
                tDurasi.setEnabled(false);
                tTglAju.setText(r.getString("service_mesin.tgl_pengajuan"));
                tNmPengaju.setText(r.getString("service_mesin.diajukan_oleh"));
                tDepartement.setText(r.getString("service_mesin.departement"));
                cbShift.setSelectedItem(r.getString("service_mesin.shift"));
            } else {
                JOptionPane.showMessageDialog(null, "Parameter tidak ditemukan ", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                bHapus.setEnabled(true);
                bUbah.setEnabled(false);
                BersihField();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pencarian ");
        }
    }
    private void tUraianProblemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tUraianProblemAncestorAdded

    }//GEN-LAST:event_tUraianProblemAncestorAdded

    private void tUraianProblemAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tUraianProblemAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tUraianProblemAncestorRemoved

    private void tKdServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKdServiceActionPerformed
        if (tKdService.getText().length() <= 9) {
            cbMesinId.requestFocus();
        } else if (tKdService.getText().length() > 9) {
            JOptionPane.showMessageDialog(null, "maksimal 9 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tKdService.requestFocus();
        }
    }//GEN-LAST:event_tKdServiceActionPerformed

    private void tKdServiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKdServiceKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_tKdServiceKeyTyped

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        hapus();
    }//GEN-LAST:event_bHapusActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        dispose();
    }//GEN-LAST:event_bTutupActionPerformed

    private void tDepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDepartementActionPerformed
        if (tDepartement.getText().length() <= 10) {
            cbShift.requestFocus();
        } else if (tDepartement.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "maksimal 10 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tDepartement.requestFocus();
        }
    }//GEN-LAST:event_tDepartementActionPerformed

    private void tDepartementKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDepartementKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tDepartementKeyTyped

    private void cbKdPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKdPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKdPekerjaanActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        BukaKoneksi();
        cari();
    }//GEN-LAST:event_bCariActionPerformed

    private void tCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_tCariKeyTyped

    private void tNmPengajuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNmPengajuActionPerformed
        if (tNmPengaju.getText().length() <= 10) {
            tDepartement.requestFocus();
        } else if (tNmPengaju.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "maksimal 10 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tNmPengaju.requestFocus();
        }
    }//GEN-LAST:event_tNmPengajuActionPerformed

    private void tNmPengajuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNmPengajuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tNmPengajuKeyTyped

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        BukaKoneksi();
        if (tKdService.getText().equals("")
                || tMesinStop.getText().equals("") || tUraianProblem.getText().equals("") || tPenyebab.getText().equals("")
                || tTindakan.getText().equals("") || tJamMulai1.getText().equals("") || tJamSelesai1.getText().equals("")
                || tDurasi.getText().equals("") || tTglAju.getText().equals("") || tNmPengaju.getText().equals("") || tDepartement.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data !");
        } else {
            ubah();
            BersihField();
            textServiceFalse();
            tombolServiceFalse();
            bTambah.setEnabled(true);
            cbCari.setEnabled(true);
            bTutup.setEnabled(true);
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        BersihField();
        textServiceTrue();
        tKdService.setText("SM");
        tMesinStop.setText(tanggal());
        tTglAju.setText(tanggal());
        bSimpan.setEnabled(true);
        bBatal.setEnabled(true);
        tKdService.requestFocus();
    }//GEN-LAST:event_bTambahActionPerformed

    private void cbNmPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNmPicActionPerformed

    }//GEN-LAST:event_cbNmPicActionPerformed

    private void cbMesinIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesinIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesinIdActionPerformed

    private void tTindakanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tTindakanAncestorAdded

    }//GEN-LAST:event_tTindakanAncestorAdded

    private void tTglAjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTglAjuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTglAjuActionPerformed

    private void tTglAjuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tTglAjuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tTglAjuKeyTyped

    private void tPenyebabAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tPenyebabAncestorAdded

    }//GEN-LAST:event_tPenyebabAncestorAdded

    private void tMesinStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMesinStopActionPerformed
        if (tMesinStop.getText().length() == 2) {
            tUraianProblem.requestFocus();
        } else if (tMesinStop.getText().length() > 2 || tMesinStop.getText().length() < 2) {
            JOptionPane.showMessageDialog(null, "harus 2 karakter, format tanggal : dd/mm/yyyy !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tMesinStop.requestFocus();
        }
    }//GEN-LAST:event_tMesinStopActionPerformed

    private void tMesinStopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tMesinStopKeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tMesinStopKeyTyped

    private void tJamSelesai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJamSelesai1ActionPerformed
        if (tJamSelesai1.getText().length() <= 2) {
            tJamSelesai2.requestFocus();
        } else if (tJamSelesai1.getText().length() > 2) {
            JOptionPane.showMessageDialog(null, "maksimal 2 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tJamSelesai1.requestFocus();
        }
    }//GEN-LAST:event_tJamSelesai1ActionPerformed

    private void tJamSelesai1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJamSelesai1KeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tJamSelesai1KeyTyped

    private void tJamSelesai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJamSelesai2ActionPerformed
        if (tJamSelesai2.getText().length() <= 2) {
            tDurasi.requestFocus();
        } else if (tJamSelesai2.getText().length() > 2) {
            JOptionPane.showMessageDialog(null, "maksimal 2 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tJamSelesai2.requestFocus();
        }
    }//GEN-LAST:event_tJamSelesai2ActionPerformed

    private void tJamSelesai2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJamSelesai2KeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tJamSelesai2KeyTyped

    private void tJamMulai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJamMulai2ActionPerformed
        if (tJamMulai2.getText().length() <= 2) {
            tJamSelesai1.requestFocus();
        } else if (tJamMulai2.getText().length() > 2) {
            JOptionPane.showMessageDialog(null, "maksimal 2 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tJamMulai2.requestFocus();
        }
    }//GEN-LAST:event_tJamMulai2ActionPerformed

    private void tJamMulai2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJamMulai2KeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tJamMulai2KeyTyped

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        bTutup.setEnabled(false);
        BukaKoneksi();
        if (tKdService.getText().equals("")
                || tMesinStop.getText().equals("") || tUraianProblem.getText().equals("") || tPenyebab.getText().equals("")
                || tTindakan.getText().equals("") || tJamMulai1.getText().equals("") || tJamSelesai1.getText().equals("")
                || tDurasi.getText().equals("") || tTglAju.getText().equals("") || tNmPengaju.getText().equals("") || tDepartement.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data !");
        } else {
            Simpan();
            BersihField();
            textServiceFalse();
            tombolServiceFalse();
            bTambah.setEnabled(true);
            cbCari.setEnabled(true);
            bTutup.setEnabled(true);
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tJamMulai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJamMulai1ActionPerformed
        if (tJamMulai1.getText().length() <= 2) {
            tJamMulai2.requestFocus();
        } else if (tJamMulai1.getText().length() > 2) {
            JOptionPane.showMessageDialog(null, "maksimal 2 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tJamMulai1.requestFocus();
        }
    }//GEN-LAST:event_tJamMulai1ActionPerformed

    private void tJamMulai1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tJamMulai1KeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tJamMulai1KeyTyped

    private void tDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDurasiActionPerformed
        if (tDurasi.getText().length() <= 6) {
            tTglAju.requestFocus();
        } else if (tDurasi.getText().length() > 6) {
            JOptionPane.showMessageDialog(null, "maksimal 6 karakter", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tDurasi.requestFocus();
        }
    }//GEN-LAST:event_tDurasiActionPerformed

    private void tDurasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDurasiKeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tDurasiKeyTyped

    private void cbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCariActionPerformed
        pilihKolomCari();
    }//GEN-LAST:event_cbCariActionPerformed
public String tanggal() {
        SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
        return tgl.format(new java.util.Date());
    }
    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        BersihField();
        textServiceFalse();
        tombolServiceFalse();
        cbCari.setEnabled(true);
        bTutup.setEnabled(true);
    }//GEN-LAST:event_bBatalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTutup;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox cbCari;
    private javax.swing.JComboBox cbKdPekerjaan;
    private javax.swing.JComboBox cbMesinId;
    private javax.swing.JComboBox cbNmPic;
    private javax.swing.JComboBox cbShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbMenit;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tDepartement;
    private javax.swing.JTextField tDurasi;
    private javax.swing.JTextField tJamMulai1;
    private javax.swing.JTextField tJamMulai2;
    private javax.swing.JTextField tJamSelesai1;
    private javax.swing.JTextField tJamSelesai2;
    private javax.swing.JTextField tKdService;
    private javax.swing.JTextField tMesinStop;
    private javax.swing.JTextField tNmPengaju;
    private javax.swing.JTextArea tPenyebab;
    private javax.swing.JTextField tTglAju;
    private javax.swing.JTextArea tTindakan;
    private javax.swing.JTextArea tUraianProblem;
    // End of variables declaration//GEN-END:variables
}
