/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package me;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author angga
 */
public class FormTeknisi extends javax.swing.JInternalFrame {

    Connection c = null;
    ResultSet r = null;

    /**
     * Creates new form FormTeknisi
     */
    public FormTeknisi() {
        initComponents();
        this.setLocation(0, 50);
        textFalse();
        tombolFalse();
        tampilTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tNik = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNmPic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();
        bCari = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        cbCari = new javax.swing.JComboBox();
        jScrollPane = new javax.swing.JScrollPane();
        bPerbarui = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setIconifiable(true);
        setTitle("Form Teknisi");

        tNik.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNikActionPerformed(evt);
            }
        });
        tNik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNikKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Teknisi");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Nama Teknisi");

        tNmPic.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tNmPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNmPicActionPerformed(evt);
            }
        });
        tNmPic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNmPicKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("NIK");

        bHapus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon delete.png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon edit.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bTambah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon tambah.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bBatal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon batal.png"))); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bSimpan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon save.png"))); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bTutup.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/tutup.png"))); // NOI18N
        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });

        bCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon cari.png"))); // NOI18N
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        tCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCariKeyTyped(evt);
            }
        });

        cbCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kolom", "NIK" }));
        cbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCariActionPerformed(evt);
            }
        });

        jScrollPane.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        bPerbarui.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bPerbarui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon refresh.png"))); // NOI18N
        bPerbarui.setText("Perbarui");
        bPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPerbaruiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bTambah)
                                        .addGap(37, 37, 37)
                                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bTutup))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bUbah)
                                        .addGap(18, 18, 18)
                                        .addComponent(bHapus))))
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(tNmPic, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel4)
                        .addGap(67, 67, 67)
                        .addComponent(tNik, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(bPerbarui))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNmPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTambah)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bSimpan)
                        .addComponent(bBatal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bHapus)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbCari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(bPerbarui)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tombolFalse() {
        bSimpan.setEnabled(false);
        bBatal.setEnabled(false);
        bUbah.setEnabled(false);
        bHapus.setEnabled(false);
        bCari.setEnabled(false);
        bTutup.setEnabled(true);
    }

    private void textFalse() {
        tNmPic.setEnabled(false);
        tNik.setEnabled(false);
        tCari.setEnabled(false);
    }

    private void textTrue() {
        tNmPic.setEnabled(true);
        tNik.setEnabled(true);
        tCari.setEnabled(true);
    }

    private void BersihField() {
        tNmPic.setText("");
        tNik.setText("");
        tCari.setText("");
    }

    private void pilihKolomCari() {
        if (cbCari.getSelectedItem().equals("Pilih Kolom")) {
            tCari.setEnabled(false);
        } else {
            tCari.setEnabled(true);
            bCari.setEnabled(true);
            tCari.requestFocus();
        }
    }

    private void BukaKoneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/maintenance", "root", "");
            System.out.println("Koneksi sukses");
        } catch (ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void Simpan() {
        String nik = tNik.getText();
        try {
            PreparedStatement pStatement = c.prepareStatement("INSERT INTO pic"
                    + "(nm_pic,nik )" + "VALUES (?,?)");
            pStatement.setString(1, tNmPic.getText());
            pStatement.setString(2, tNik.getText());
            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this,
                        "Penambahan sukses", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                BersihField();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Penambahan gagal", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            c.close();
            tampilTabel();
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
            JOptionPane.showMessageDialog(null, "Gagal menyimpan \nNIK kembar :" + "\nNIK [ " + nik + " ] telah ada, "
                    + "atau data yang Anda masukkan tidak sesuai format dengan yang diminta !");
            tNik.setFocusable(true);
        }
    }

    private void ubah() {
        String nik = tNik.getText();
        String nama = tNmPic.getText();
        try {
            String message = "Apakah anda yakin akan mengubah data" + "\ndengan nik : " + nik + "\ndan nama pic : " + nama + "?";
            int pesan = JOptionPane.showConfirmDialog(null, message, "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
            if (pesan == 0) {
            PreparedStatement pStatement = c.prepareStatement("UPDATE pic SET nm_pic=?"
                    + " WHERE nik=?");

            pStatement.setString(1, tNmPic.getText());
            pStatement.setString(2, tNik.getText());
            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Edit sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                BersihField();
            } else {
                JOptionPane.showMessageDialog(null, "Edit gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            textFalse();
            tombolFalse();
            tampilTabel();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal, atau data yang Anda masukkan tidak sesuai dengan yang diminta !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void hapus() {
        String nik = tNik.getText();
        String nama = tNmPic.getText();
        try {
            String message = "Apakah anda yakin akan menghapus semua data" + "\ndengan nik : " + nik + "\ndan nama pic : " + nama + "?";
            int pesan = JOptionPane.showConfirmDialog(null, message, "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
            if (pesan == 0) {
                PreparedStatement pStatement = c.prepareStatement("DELETE FROM pic WHERE nik=?");
                pStatement.setString(1, tNik.getText());
                if (pStatement.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this,
                            "berhasil menghapus", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                    BersihField();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "hapus gagal", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                pStatement.close();
                c.close();
                BersihField();
                tampilTabel();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal " + e.toString());
        }
    }

    private void cari() {
        String param = tCari.getText();
        try {
            String kolom;
            if (cbCari.getSelectedItem().equals("NIK")) {
                kolom = "nik";
            } else {
                kolom = "";
            }
            Statement s = c.createStatement();
            String sql = "Select * from pic Where " + kolom + " ='" + param + "'";
            r = s.executeQuery(sql);
            if (r.next()) {
                textTrue();
                bUbah.setEnabled(true);
                bHapus.setEnabled(true);
                tNmPic.setText(r.getString("nm_pic"));
                tNik.setText(r.getString("nik"));
            } else {
                JOptionPane.showMessageDialog(null, "Parameter tidak ditemukan !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                bHapus.setEnabled(true);
                bUbah.setEnabled(false);
                BersihField();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pencarian ");
        }
    }
    private void tNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNikActionPerformed
        if (tNik.getText().length() == 8) {
            bSimpan.requestFocus();
        } else if (tNik.getText().length() < 8 || tNik.getText().length() > 8) {
            JOptionPane.showMessageDialog(null, "harus 8 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tNik.setFocusable(true);
        }
    }//GEN-LAST:event_tNikActionPerformed

    private void tNmPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNmPicActionPerformed
        if (tNmPic.getText().length() <= 10) {
            tNik.requestFocus();
        } else if (tNmPic.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "maksimal 10 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tNmPic.requestFocus();
        }
    }//GEN-LAST:event_tNmPicActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        hapus();
    }//GEN-LAST:event_bHapusActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        BukaKoneksi();
        if (tNmPic.getText().equals("") || tNik.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data !");
        } else {
            ubah();
            BersihField();
            textFalse();
            tombolFalse();
            bTambah.setEnabled(true);
            cbCari.setEnabled(true);
            bTutup.setEnabled(true);
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        BersihField();
        textTrue();
        bSimpan.setEnabled(true);
        bBatal.setEnabled(true);
        tNmPic.requestFocus();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        BersihField();
        textFalse();
        tombolFalse();
        cbCari.setEnabled(true);
        bTutup.setEnabled(true);
    }//GEN-LAST:event_bBatalActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        bTutup.setEnabled(false);
        BukaKoneksi();
        if (tNmPic.getText().equals("") || tNik.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data !");
        } else {
            Simpan();
            BersihField();
            textFalse();
            tombolFalse();
            bTambah.setEnabled(true);
            cbCari.setEnabled(true);
            bTutup.setEnabled(true);
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        dispose();
    }//GEN-LAST:event_bTutupActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        BukaKoneksi();
        cari();
    }//GEN-LAST:event_bCariActionPerformed

    private void tCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_tCariKeyTyped

    private void cbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCariActionPerformed
        pilihKolomCari();
    }//GEN-LAST:event_cbCariActionPerformed

    private void tNikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNikKeyTyped
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tNikKeyTyped

    private void tNmPicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNmPicKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_tNmPicKeyTyped

    private void bPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPerbaruiActionPerformed
        tampilTabel();
    }//GEN-LAST:event_bPerbaruiActionPerformed
private Object[][] getData() {

        String user = "root";
        String pwd = "";
        String host = "localhost";
        String db = "maintenance";

        Object[][] data1 = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            String urlValue = "jdbc:mysql://" + host + "/"
                    + db + "?user=" + user
                    + "&password=" + pwd;

            c = DriverManager.getConnection(urlValue);

            Statement st = c.createStatement();
            r = st.executeQuery(
                    "Select * from pic");

            r.last();
            int rowCount = r.getRow();
            r.beforeFirst();

            data1 = new Object[rowCount][3];
            int no = -1, angka = 1;
            while (r.next()) {
                no = no + 1;
                data1[no][0] = angka + ".";
                data1[no][1] = r.getString("nm_pic");
                data1[no][2] = r.getString("nik");
                angka = angka + 1;
            }

            st.close();
            c.close();

        } catch (ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());

        }

        return data1;
    }
private void tampilTabel() {

        String[] columnNames = {"No.", "Nama Teknisi", "NIK"};

        JTable table = new JTable(
                getData(), columnNames);

        jScrollPane.setViewportView(table);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bPerbarui;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTutup;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox cbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tNik;
    private javax.swing.JTextField tNmPic;
    // End of variables declaration//GEN-END:variables
}
