/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package me;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author angga
 */
public class FormUser extends javax.swing.JInternalFrame {

    Connection c = null;
    ResultSet r = null;

    /**
     * Creates new form FormUser
     */
    public FormUser() {
        initComponents();
        this.setLocation(0, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        tNik = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        tJabatan = new javax.swing.JTextField();
        cbKdUser = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bCari = new javax.swing.JButton();
        tUsernameCari = new javax.swing.JTextField();
        tPasswordCari = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setClosable(true);
        setIconifiable(true);
        setTitle("Form User");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form User");

        tUsername.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameActionPerformed(evt);
            }
        });

        tNik.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNikActionPerformed(evt);
            }
        });
        tNik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNikKeyTyped(evt);
            }
        });

        tPassword.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        tJabatan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJabatanActionPerformed(evt);
            }
        });

        cbKdUser.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbKdUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100", "200", "300" }));

        jLabel2.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jLabel2.setText("Nama User");

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jLabel5.setText("Jabatan");

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jLabel6.setText("Kode User");

        jLabel8.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jLabel8.setText("Masukkan nama user dan password anda !");

        bHapus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon delete.png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon edit.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bSimpan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon save.png"))); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon cari.png"))); // NOI18N
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        tUsernameCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tUsernameCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameCariActionPerformed(evt);
            }
        });

        tPasswordCari.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("Nama User");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bSimpan)
                                .addGap(74, 74, 74)
                                .addComponent(bUbah))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel9))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tPasswordCari, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tUsernameCari, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bCari, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(bHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(66, 66, 66)
                                        .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tNik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbKdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus)
                    .addComponent(bUbah)
                    .addComponent(bSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tUsernameCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tPasswordCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bCari)
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void BersihField() {
        tUsername.setText("");
        tNik.setText("");
        tPassword.setText("");
        tJabatan.setText("");
    }

    private void BukaKoneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/maintenance", "root", "");
            System.out.println("Koneksi sukses");
        } catch (ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void Simpan() {
        String pass = new String(tPassword.getPassword());
        String nik = tNik.getText();
        try {
            PreparedStatement pStatement = c.prepareStatement("INSERT INTO user"
                    + "(username,nik,pswd,kd_user,jabatan)" + "VALUES (?,?,?,?,?)");
            pStatement.setString(1, tUsername.getText());
            pStatement.setString(2, tNik.getText());
            pStatement.setString(3, pass);
            pStatement.setString(4, cbKdUser.getSelectedItem().toString());
            pStatement.setString(5, tJabatan.getText());
            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this,
                        "Penambahan user sukses", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                BersihField();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Penambahan user gagal", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            c.close();
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
            JOptionPane.showMessageDialog(null, "Gagal menyimpan \nNIK kembar :" + "\nNIK [ " + nik + " ] telah ada, "
                    + "atau data yang Anda masukkan tidak sesuai format dengan yang diminta !");
            tNik.setFocusable(true);
        }
    }

    private void ubah() {
        String pass = new String(tPassword.getPassword());
        try {
            PreparedStatement pStatement = c.prepareStatement("UPDATE user SET username=?,"
                    + "pswd=?,kd_user=?,jabatan=? WHERE nik=?");

            pStatement.setString(1, tUsername.getText());
            pStatement.setString(2, pass);
            pStatement.setString(3, cbKdUser.getSelectedItem().toString());
            pStatement.setString(4, tJabatan.getText());
            pStatement.setString(5, tNik.getText());
            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Edit User sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                BersihField();
            } else {
                JOptionPane.showMessageDialog(null, "Edit User gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal, atau data yang Anda masukkan tidak sesuai dengan yang diminta !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void hapus() {
        String user = tUsername.getText();
        try {
            String message = "Apakah anda yakin akan menghapus semua data user" + "\ndengan nama user : " + user + " ?";
            int pesan = JOptionPane.showConfirmDialog(null, message, "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
            if (pesan == 0) {
                PreparedStatement pStatement = c.prepareStatement("DELETE FROM user WHERE nik=?");
                pStatement.setString(1, tNik.getText());

                if (pStatement.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this,
                            "berhasil menghapus", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                    BersihField();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "hapus gagal", "Informasi",
                            JOptionPane.INFORMATION_MESSAGE);
                }

                pStatement.close();
                c.close();

                BersihField();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal " + e.toString());
        }
    }

    private void cari() {
        try {
            String user = tUsernameCari.getText();
            String pass = new String(tPasswordCari.getPassword());
            Statement s = c.createStatement();
            String sql = "Select * from user Where username='" + user + "' And pswd='" + pass + "'";
            r = s.executeQuery(sql);
            if (r.next()) {
                bUbah.setEnabled(true);
                bHapus.setEnabled(true);
                tUsername.setText(r.getString("username"));
                tNik.setText(r.getString("nik"));
                tPassword.setText(r.getString("pswd"));
                cbKdUser.setSelectedItem(r.getString("kd_user"));
                tJabatan.setText(r.getString("jabatan"));
            } else {
                JOptionPane.showMessageDialog(null, "Parameter tidak ditemukan ! ", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                bHapus.setEnabled(false);
                bUbah.setEnabled(false);
                BersihField();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Kesalahan pencarian ");
        }
    }
    private void tNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNikActionPerformed
        if (tNik.getText().length() <= 15) {
            //tThBuat.requestFocus();
        } else if (tNik.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "maksimal 15 karakter", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tNik.requestFocus();
        }
    }//GEN-LAST:event_tNikActionPerformed

    private void tUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameActionPerformed
        if (tUsername.getText().length() <= 7) {
            tNik.requestFocus();
        } else if (tUsername.getText().length() > 7) {
            JOptionPane.showMessageDialog(null, "maksimal 7 karakter", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tUsername.requestFocus();
        }
    }//GEN-LAST:event_tUsernameActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        String pass = new String(tPassword.getPassword());
        BukaKoneksi();
        if (tUsername.getText().equals("") || tNik.getText().equals("") || pass.equals("") || tJabatan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data!");
        } else {
            Simpan();
            BersihField();
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        String pass = new String(tPassword.getPassword());
        BukaKoneksi();
        if (tUsername.getText().equals("") || tNik.getText().equals("") || pass.equals("") || tJabatan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data!");
        } else {
            ubah();
            BersihField();
        }

    }//GEN-LAST:event_bUbahActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        BukaKoneksi();
        cari();
    }//GEN-LAST:event_bCariActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        hapus();
    }//GEN-LAST:event_bHapusActionPerformed

    private void tUsernameCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsernameCariActionPerformed

    private void tJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJabatanActionPerformed

    private void tNikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNikKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tNikKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox cbKdUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField tJabatan;
    private javax.swing.JTextField tNik;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JPasswordField tPasswordCari;
    private javax.swing.JTextField tUsername;
    private javax.swing.JTextField tUsernameCari;
    // End of variables declaration//GEN-END:variables
}
