/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package me;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author angga
 */
public class FormMenuUser extends javax.swing.JFrame {
Connection c = null;
    Statement s = null;
    ResultSet r = null;
    /**
     * Creates new form formInputMesin
     */
    public FormMenuUser() {
        super("Form Menu User");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        M_FMesin = new javax.swing.JMenuItem();
        M_Form_Pic = new javax.swing.JMenuItem();
        M_Form_Pekerjaan = new javax.swing.JMenuItem();
        M_Exit1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        M_Input_Serv_Mesin1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        M_Tabel_Serv_Mesin = new javax.swing.JMenuItem();
        M_Tabel_Detil_Service_Mesin = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        M_About_App = new javax.swing.JMenuItem();
        M_Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktop.setBackground(new java.awt.Color(0, 153, 153));

        jMenu1.setText("Master");

        M_FMesin.setText("Mesin");
        M_FMesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_FMesinActionPerformed(evt);
            }
        });
        jMenu1.add(M_FMesin);

        M_Form_Pic.setText("Teknisi");
        M_Form_Pic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Form_PicActionPerformed(evt);
            }
        });
        jMenu1.add(M_Form_Pic);

        M_Form_Pekerjaan.setText("Pekerjaan");
        M_Form_Pekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Form_PekerjaanActionPerformed(evt);
            }
        });
        jMenu1.add(M_Form_Pekerjaan);

        M_Exit1.setText("Exit");
        M_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Exit1ActionPerformed(evt);
            }
        });
        jMenu1.add(M_Exit1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Transaksi");

        M_Input_Serv_Mesin1.setText("Service Mesin");
        M_Input_Serv_Mesin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Input_Serv_Mesin1ActionPerformed(evt);
            }
        });
        jMenu4.add(M_Input_Serv_Mesin1);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Tabel");

        M_Tabel_Serv_Mesin.setText("Tabel Service Mesin");
        M_Tabel_Serv_Mesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Tabel_Serv_MesinActionPerformed(evt);
            }
        });
        jMenu6.add(M_Tabel_Serv_Mesin);

        M_Tabel_Detil_Service_Mesin.setText("Tabel Detil Service Mesin");
        M_Tabel_Detil_Service_Mesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Tabel_Detil_Service_MesinActionPerformed(evt);
            }
        });
        jMenu6.add(M_Tabel_Detil_Service_Mesin);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("About App");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        M_About_App.setText("About App");
        M_About_App.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_About_AppActionPerformed(evt);
            }
        });
        jMenu7.add(M_About_App);

        M_Logout.setText("Logout");
        M_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_LogoutActionPerformed(evt);
            }
        });
        jMenu7.add(M_Logout);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1273, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

void formMesinFalse() {
        M_FMesin.setEnabled(false);
    }
void formMesinTrue() {
        M_FMesin.setEnabled(true);
    }
    protected void FormMesinUser() {
        FormMesinUser fm = new FormMesinUser();
        fm.setVisible(true);
        jDesktop.add(fm);
        try {
            //membuat internalFrame baru terpilih
            fm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

                                              
    private void input_service_mesin() {
        FormServiceMesinUser fsm = new FormServiceMesinUser();
        fsm.setVisible(true);
        jDesktop.add(fsm);
        try {
            fsm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }
private void tabelServiceMesin() {
        TabelServiceMesin tsm = new TabelServiceMesin();
        tsm.setVisible(true);
        jDesktop.add(tsm);
        try {
            tsm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

    private void tabelDetilServiceMesin() {
        TabelDetilServiceMesin tdsm = new TabelDetilServiceMesin();
        tdsm.setVisible(true);
        jDesktop.add(tdsm);
        try {
            tdsm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }
    private void formTeknisiUser() {
        FormTeknisiUser fP = new FormTeknisiUser();
        fP.setVisible(true);
        jDesktop.add(fP);
        try {
            fP.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

private void formPekerjaanUser() {
        FormPekerjaanUser fPj = new FormPekerjaanUser();
        fPj.setVisible(true);
        jDesktop.add(fPj);
        try {
            fPj.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }
private void aboutApp(){
    AboutApp aA = new AboutApp();
    aA.setVisible(true);
    jDesktop.add(aA);
    try{
    aA.setSelected(true);
    }catch(java.beans.PropertyVetoException e){
    }
    }
    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void M_FMesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_FMesinActionPerformed
        FormMesinUser();
    }//GEN-LAST:event_M_FMesinActionPerformed

    private void M_Form_PicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Form_PicActionPerformed
        formTeknisiUser();
    }//GEN-LAST:event_M_Form_PicActionPerformed

    private void M_Form_PekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Form_PekerjaanActionPerformed
        formPekerjaanUser();
    }//GEN-LAST:event_M_Form_PekerjaanActionPerformed

    private void M_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Exit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_M_Exit1ActionPerformed

    private void M_Input_Serv_Mesin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Input_Serv_Mesin1ActionPerformed
        input_service_mesin();
    }//GEN-LAST:event_M_Input_Serv_Mesin1ActionPerformed

    private void M_Tabel_Serv_MesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Tabel_Serv_MesinActionPerformed
        tabelServiceMesin();
    }//GEN-LAST:event_M_Tabel_Serv_MesinActionPerformed

    private void M_Tabel_Detil_Service_MesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Tabel_Detil_Service_MesinActionPerformed
        tabelDetilServiceMesin();
    }//GEN-LAST:event_M_Tabel_Detil_Service_MesinActionPerformed

    private void M_About_AppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_About_AppActionPerformed
        aboutApp();
    }//GEN-LAST:event_M_About_AppActionPerformed

    private void M_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_LogoutActionPerformed
        dispose();
        FormLogin fl = new FormLogin();
        fl.setLocationRelativeTo(this);
        fl.setVisible(true);
    }//GEN-LAST:event_M_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FormMenuUser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem M_About_App;
    private javax.swing.JMenuItem M_Exit1;
    private javax.swing.JMenuItem M_FMesin;
    private javax.swing.JMenuItem M_Form_Pekerjaan;
    private javax.swing.JMenuItem M_Form_Pic;
    private javax.swing.JMenuItem M_Input_Serv_Mesin1;
    private javax.swing.JMenuItem M_Logout;
    private javax.swing.JMenuItem M_Tabel_Detil_Service_Mesin;
    private javax.swing.JMenuItem M_Tabel_Serv_Mesin;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
