/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package me;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author angga
 */
public class FormPekerjaanUser extends javax.swing.JInternalFrame {
 Connection c = null;
    ResultSet r = null;
    /**
     * Creates new form FormPekerjaanUser
     */
    public FormPekerjaanUser() {
        initComponents();
        this.setLocation(0, 100);
        textFalse();
        tombolFalse();
        tampilTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSimpan = new javax.swing.JButton();
        tGolPekerjaan = new javax.swing.JTextField();
        bBatal = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bTutup = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        tKdPekerjaan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bPerbarui = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setIconifiable(true);
        setTitle("Form Pekerjaan");

        bSimpan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon save.png"))); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        tGolPekerjaan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tGolPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tGolPekerjaanActionPerformed(evt);
            }
        });
        tGolPekerjaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tGolPekerjaanKeyTyped(evt);
            }
        });

        bBatal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon batal.png"))); // NOI18N
        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bTambah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon tambah.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Golongan Pekerjaan");

        bTutup.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/tutup.png"))); // NOI18N
        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });

        jScrollPane.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Pekerjaan");

        tKdPekerjaan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tKdPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKdPekerjaanActionPerformed(evt);
            }
        });
        tKdPekerjaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tKdPekerjaanKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Kode Pekerjaan");

        bPerbarui.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        bPerbarui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/ikon refresh.png"))); // NOI18N
        bPerbarui.setText("Perbarui");
        bPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPerbaruiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(bTambah)
                                    .addGap(49, 49, 49)
                                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addComponent(bTutup))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(55, 55, 55)
                                    .addComponent(tKdPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel4)
                                    .addGap(50, 50, 50)
                                    .addComponent(tGolPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(bPerbarui)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tKdPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tGolPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(bTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSimpan)
                    .addComponent(bBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bPerbarui)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void tombolFalse() {
        bSimpan.setEnabled(false);
        bBatal.setEnabled(false);
        bTutup.setEnabled(true);
    }

    private void textFalse() {
        tKdPekerjaan.setEnabled(true);
        tGolPekerjaan.setEnabled(false);
    }

    private void textTrue() {
        tKdPekerjaan.setEnabled(true);
        tGolPekerjaan.setEnabled(true);
    }

    private void BersihField() {
        tKdPekerjaan.setText("");
        tGolPekerjaan.setText("");
    }

    private void BukaKoneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/maintenance", "root", "");
            System.out.println("Koneksi sukses");
        } catch (ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void Simpan() {
        String golPk = tKdPekerjaan.getText();
        try {
            PreparedStatement pStatement = c.prepareStatement("INSERT INTO jenis_pekerjaan"
                    + "(kd_pekerjaan,gol_pekerjaan"
                    + ")" + "VALUES (?,?)");
            pStatement.setString(1, tKdPekerjaan.getText());
            pStatement.setString(2, tGolPekerjaan.getText());
            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this,
                        "Penambahan sukses", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                BersihField();
                tampilTabel();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Penambahan gagal", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            c.close();
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
            JOptionPane.showMessageDialog(null, "Gagal menyimpan \nGolongan Pekerjaan kembar :" + "\nKode Pekerjaan [ " + golPk + " ] telah ada, "
                    + "atau data yang Anda masukkan tidak sesuai format dengan yang diminta !");
            tKdPekerjaan.setFocusable(true);
        }
    }
    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        bTutup.setEnabled(false);
        BukaKoneksi();
        if (tKdPekerjaan.getText().equals("") || tGolPekerjaan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi data !");
        } else {
            Simpan();
            BersihField();
            textFalse();
            tombolFalse();
            bTambah.setEnabled(true);
            bTutup.setEnabled(true);
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tGolPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tGolPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tGolPekerjaanActionPerformed

    private void tGolPekerjaanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tGolPekerjaanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tGolPekerjaanKeyTyped

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        BersihField();
        textFalse();
        tombolFalse();
        bTutup.setEnabled(true);
    }//GEN-LAST:event_bBatalActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        BersihField();
        textTrue();
        tKdPekerjaan.setText("PK");
        bSimpan.setEnabled(true);
        bBatal.setEnabled(true);
        tKdPekerjaan.requestFocus();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        dispose();
    }//GEN-LAST:event_bTutupActionPerformed

    private void tKdPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKdPekerjaanActionPerformed
        if (tKdPekerjaan.getText().length() <= 7) {
            tGolPekerjaan.requestFocus();
        } else if (tKdPekerjaan.getText().length() > 7) {
            JOptionPane.showMessageDialog(null, "maksimal 7 karakter !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tKdPekerjaan.requestFocus();
        }
    }//GEN-LAST:event_tKdPekerjaanActionPerformed

    private void tKdPekerjaanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKdPekerjaanKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_tKdPekerjaanKeyTyped
private Object[][] getData() {

        String user = "root";
        String pwd = "";
        String host = "localhost";
        String db = "maintenance";

        Object[][] data1 = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            String urlValue = "jdbc:mysql://" + host + "/"
                    + db + "?user=" + user
                    + "&password=" + pwd;

            c = DriverManager.getConnection(urlValue);

            Statement st = c.createStatement();
            r = st.executeQuery(
                    "Select * from jenis_pekerjaan");

            r.last();
            int rowCount = r.getRow();
            r.beforeFirst();

            data1 = new Object[rowCount][3];
            int no = -1, angka = 1;
            while (r.next()) {
                no = no + 1;
                data1[no][0] = angka + ".";
                data1[no][1] = r.getString("kd_pekerjaan");
                data1[no][2] = r.getString("gol_pekerjaan");
                angka = angka + 1;
            }

            st.close();
            c.close();

        } catch (ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());

        }

        return data1;
    }

    private void tampilTabel() {

        String[] columnNames = {"No.", "KODE PEKERJAAN", "GOLONGAN PEKERJAAN"};

        JTable table = new JTable(
                getData(), columnNames);

        jScrollPane.setViewportView(table);
    }
    private void bPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPerbaruiActionPerformed
        tampilTabel();
    }//GEN-LAST:event_bPerbaruiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bPerbarui;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField tGolPekerjaan;
    private javax.swing.JTextField tKdPekerjaan;
    // End of variables declaration//GEN-END:variables
}
