/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package me;

/**
 *
 * @author angga
 */
public class FormMenuManajer extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuManajer
     */
    public FormMenuManajer() {
        super("Form Menu Manajer");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        M_Lap_Per_Mesin = new javax.swing.JMenuItem();
        M_Lap_Serv_Per_Hari = new javax.swing.JMenuItem();
        M_Lap_Serv_Per_Periode = new javax.swing.JMenuItem();
        M_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        M_Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktop.setBackground(new java.awt.Color(0, 153, 153));

        jMenu1.setText("Laporan");

        M_Lap_Per_Mesin.setText("Laporan Service Per Mesin");
        M_Lap_Per_Mesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Lap_Per_MesinActionPerformed(evt);
            }
        });
        jMenu1.add(M_Lap_Per_Mesin);

        M_Lap_Serv_Per_Hari.setText("Laporan Service Per Hari");
        M_Lap_Serv_Per_Hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Lap_Serv_Per_HariActionPerformed(evt);
            }
        });
        jMenu1.add(M_Lap_Serv_Per_Hari);

        M_Lap_Serv_Per_Periode.setText("Laporan Service Per Periode");
        M_Lap_Serv_Per_Periode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_Lap_Serv_Per_PeriodeActionPerformed(evt);
            }
        });
        jMenu1.add(M_Lap_Serv_Per_Periode);

        M_Exit.setText("Exit");
        M_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(M_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About App");

        jMenuItem7.setText("About This App");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        M_Logout.setText("Logout");
        M_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_LogoutActionPerformed(evt);
            }
        });
        jMenu2.add(M_Logout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formCetakPerMesin() {
        FormCetakPerMesin fcpm = new FormCetakPerMesin();
        fcpm.setVisible(true);
        jDesktop.add(fcpm);
        try {
            fcpm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

    private void formLaporanPeriode() {
        FormLaporanPeriode FLP = new FormLaporanPeriode();
        FLP.setVisible(true);
        jDesktop.add(FLP);
        try {
            FLP.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

    private void formLaporanPerHari() {
        FormLaporanPerHari FLPH = new FormLaporanPerHari();
        FLPH.setVisible(true);
        jDesktop.add(FLPH);
        try {
            FLPH.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }
    private void M_Lap_Per_MesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Lap_Per_MesinActionPerformed
        formCetakPerMesin();
    }//GEN-LAST:event_M_Lap_Per_MesinActionPerformed

    private void M_Lap_Serv_Per_HariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Lap_Serv_Per_HariActionPerformed
        formLaporanPerHari();
    }//GEN-LAST:event_M_Lap_Serv_Per_HariActionPerformed

    private void M_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_LogoutActionPerformed
        dispose();
        FormLogin fl = new FormLogin();
        fl.setLocationRelativeTo(this);
        fl.setVisible(true);
    }//GEN-LAST:event_M_LogoutActionPerformed
private void aboutApp(){
    AboutApp aA = new AboutApp();
    aA.setVisible(true);
    jDesktop.add(aA);
    try{
    aA.setSelected(true);
    }catch(java.beans.PropertyVetoException e){
    }
    }
    private void M_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_M_ExitActionPerformed

    private void M_Lap_Serv_Per_PeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_Lap_Serv_Per_PeriodeActionPerformed
        formLaporanPeriode();
    }//GEN-LAST:event_M_Lap_Serv_Per_PeriodeActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        aboutApp();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormMenuManajer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem M_Exit;
    private javax.swing.JMenuItem M_Lap_Per_Mesin;
    private javax.swing.JMenuItem M_Lap_Serv_Per_Hari;
    private javax.swing.JMenuItem M_Lap_Serv_Per_Periode;
    private javax.swing.JMenuItem M_Logout;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
